[package]
name = "test_coprocessor_plugin_api"
version = "0.0.1"
edition = "2018"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
