[package]
name = "example_plugin"
version = "0.1.0"
edition = "2018"
publish = false

[lib]
crate-type = ["dylib"]

[dependencies]
coprocessor_plugin_api = { path = "../../coprocessor_plugin_api" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
futures = "0.3"
